#!/bin/bash

ENV_FILE="apps/sample-app/.env"
LOCAL_PROPERTIES_FILE="apps/sample-app/android/local.properties"

ENV_CONTENT="GOOGLE_CLIENT_ID=$1
MICROSOFT_CLIENT_ID=$2
DROPBOX_CLIENT_ID=$4
DROPBOX_CLIENT_SECRET=$5"

LOCAL_PROPERTIES_CONTENT="GOOGLE_CLIENT_ID=$1
MICROSOFT_CLIENT_ID=$2
MICROSOFT_SIGNATURE_HASH=$3
DROPBOX_CLIENT_ID=$4"

echo "$ENV_CONTENT" >> "$ENV_FILE"
echo "$LOCAL_PROPERTIES_CONTENT" >> "$LOCAL_PROPERTIES_FILE"